<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HW8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="HW8_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW8_files/libs/quarto-html/quarto.js"></script>
<script src="HW8_files/libs/quarto-html/popper.min.js"></script>
<script src="HW8_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW8_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW8_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW8_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW8_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW8_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW8</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>-- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>v ggplot2 3.3.5     v purrr   0.3.4
v tibble  3.1.4     v dplyr   1.0.7
v tidyr   1.1.3     v stringr 1.4.0
v readr   2.0.1     v forcats 0.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"table11_1_modified.csv"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>dt.l <span class="ot">&lt;-</span> <span class="fu">melt</span>(dat, <span class="at">id.vars=</span><span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"group"</span>), <span class="at">measure.vars=</span><span class="fu">paste</span>(<span class="st">"week"</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,<span class="at">sep=</span><span class="st">""</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">variable.name=</span><span class="st">"week"</span>, <span class="at">value.name=</span><span class="st">"fas"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>dt.l<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">recode</span>(dt.l<span class="sc">$</span>week, <span class="st">"week1"</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">"week2"</span><span class="ot">=</span><span class="dv">2</span>, <span class="st">"week3"</span><span class="ot">=</span><span class="dv">3</span>, <span class="st">"week4"</span><span class="ot">=</span><span class="dv">4</span>, <span class="st">"week5"</span><span class="ot">=</span><span class="dv">5</span>, <span class="st">"week6"</span><span class="ot">=</span><span class="dv">6</span>, <span class="st">"week7"</span><span class="ot">=</span><span class="dv">7</span>, <span class="st">"week8"</span><span class="ot">=</span><span class="dv">8</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>dt.l <span class="ot">&lt;-</span> dt.l[<span class="fu">order</span>(dt.l<span class="sc">$</span>id),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<section id="part-a" class="level2">
<h2 class="anchored" data-anchor-id="part-a">Part A</h2>
<p>Consider “Model 3” in the lecture note. Your collaborator Dr.&nbsp;Smith Lee, a clinician, email you to ask you explain the random intercept and random slope in the model. Write a response email to Dr.&nbsp;Lee. Use plain language as much as possible without numerical results in your reply.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(fas <span class="sc">~</span> time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> time<span class="sc">|</span> id), <span class="at">data=</span>dt.l)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: fas ~ time + (1 + time | id)
   Data: dt.l

REML criterion at convergence: 1335

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.8482 -0.5401 -0.0040  0.4944  3.2309 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 190.225  13.792        
          time          8.273   2.876   -0.17
 Residual              27.638   5.257        
Number of obs: 192, groups:  id, 24

Fixed effects:
            Estimate Std. Error t value
(Intercept)   27.637      2.937   9.410
time           5.030      0.610   8.245

Correlation of Fixed Effects:
     (Intr)
time -0.225</code></pre>
</div>
</div>
<p>In this model we are predicting the functional ability scores (FAS) of an individual. We allow for a random intercept, meaning that we expect individuals to have a random effect on the intercepts of the model, or the predicted FAS value for an individual at time = 0.</p>
<p>We also are allowing for a random slope, meaning that we are allowing for individuals to have different effects on the slope of the model, or, in other words, an individuals effect on FAS over time changes different between individuals.</p>
</section>
<section id="part-b" class="level2">
<h2 class="anchored" data-anchor-id="part-b">Part B</h2>
<p>Consider “Model 3” in the lecture note. You now want to study if the temporal effect differs by group. Consider GROUP to be a continuous variable. Assume random intercept and random slope for the time effect only in the model. Write down the linear mixed effects model. Fit the model to the provided dataset. Interpret the fixed effect for the interaction. In addition, what are the estimated variances of random effects? How do you interpret them?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dt.l<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">unclass</span>(<span class="fu">as.factor</span>(dt.l<span class="sc">$</span>group))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(fas <span class="sc">~</span> time <span class="sc">+</span> group <span class="sc">+</span> time<span class="sc">*</span>group <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> time<span class="sc">|</span>id), <span class="at">data =</span> dt.l)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: fas ~ time + group + time * group + (1 + time | id)
   Data: dt.l

REML criterion at convergence: 1322.4

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.8242 -0.5415  0.0040  0.5127  3.2420 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 id       (Intercept) 181.966  13.489        
          time          6.475   2.545   -0.03
 Residual              27.638   5.257        
Number of obs: 192, groups:  id, 24

Fixed effects:
            Estimate Std. Error t value
(Intercept)  17.7798     7.6137   2.335
time          8.5119     1.4423   5.901
group         4.9286     3.5244   1.398
time:group   -1.7411     0.6677  -2.608

Correlation of Fixed Effects:
           (Intr) time   group 
time       -0.102              
group      -0.926  0.095       
time:group  0.095 -0.926 -0.102</code></pre>
</div>
</div>
<p><span class="math display">\[
Y_{ij} = \beta_0 + a_i + (\beta_1 + b_i)t_{ij} + \beta_2*\text{Group} + \beta_3t_{ij}*\text{Group} + e_{ij}
\]</span></p>
<p><span class="math display">\[
\text{For a given time, }t:
\\
\text{Group} = 1: \beta_0 + a_i + (\beta_1 + b_i + \beta_3)t + \beta_2
\]</span></p>
<p><span class="math display">\[
\text{Group} = 0: \beta_0 + a_i (\beta_1 + b_i) t
\\
\text{The difference between these two is: }\beta_3t+\beta_2
\]</span></p>
<p><span class="math display">\[
\text{For a given time, }t + 1:
\\
\text{Group} = 1: \beta_0 + a_i + (\beta_1 + b_i + \beta_3)(t+1) + \beta_2
\]</span></p>
<p><span class="math display">\[
\text{Group} = 0: \beta_0 + a_i (\beta_1 + b_i) (t+1)
\\
\text{The difference between these two is: }\beta_3(t+1)+\beta_2
\]</span></p>
<p>The difference of the differences as shown above is <span class="math inline">\(\neq0\)</span>, so a 1 unit increase in time changes the effect of group on FAS, by a value of <span class="math inline">\(\beta_3\)</span>.</p>
<p>The estimated variance of random effects for id is 181.966, and the variance for the random effect of time is 6.475. The variance is pretty large for for id, meaning our intercept varies a large amount between individuals. The variance for time or slope is pretty small, meaning the slope over time does not change particularly a lot between individuals.</p>
</section>
<section id="part-c" class="level2">
<h2 class="anchored" data-anchor-id="part-c">Part C</h2>
<p>Now, add a random slope for the group effect (so there are two random slopes) to the model in (b). Write down the updated model. Fit the model to the provided dataset. How do you explain the random slope for the group effect to Dr.&nbsp;Lee? Compare fixed effect coefficients in (b) and (c). Are they the same? Now, compared with results in (b), is the inference for the fixed effect of the interaction changed? Explain it. In addition, what are the estimated variances of random effects? Which main covariate effect does vary more across individuals, time or group?</p>
<p><span class="math display">\[
Y_{ij} = \beta_0 + a_i + (\beta_1 + b_i)t_{ij} + (\beta_2 + c_i)*\text{Group} + \beta_3t_{ij}*\text{Group} + e_{ij}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit3c <span class="ot">&lt;-</span> <span class="fu">lmer</span>(fas <span class="sc">~</span> time <span class="sc">+</span> group <span class="sc">+</span> time<span class="sc">*</span>group <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> time <span class="sc">+</span> group<span class="sc">|</span>id), <span class="at">data =</span> dt.l)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: fas ~ time + group + time * group + (1 + time + group | id)
   Data: dt.l

REML criterion at convergence: 1320.3

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.8209 -0.5266  0.0199  0.5041  3.2518 

Random effects:
 Groups   Name        Variance Std.Dev. Corr       
 id       (Intercept) 309.242  17.585              
          time          6.487   2.547   -0.70      
          group        32.185   5.673   -0.68  1.00
 Residual              27.622   5.256              
Number of obs: 192, groups:  id, 24

Fixed effects:
            Estimate Std. Error t value
(Intercept)  19.3877     7.7937   2.488
time          8.1286     1.4112   5.760
group         4.2669     3.5704   1.195
time:group   -1.5494     0.6507  -2.381

Correlation of Fixed Effects:
           (Intr) time   group 
time       -0.363              
group      -0.928  0.260       
time:group  0.252 -0.922 -0.153</code></pre>
</div>
</div>
<p>To explain the random slope for group effect to Dr.&nbsp;Lee, I would say that each group has its own effect on slope across time. Each individual has its own slope, but for a 1 unit increase in group and time, FAS increases by 4.27.</p>
<p>The fixed effects coefficients are somewhat similar, the first model intercept value is 17.78, and the second model is 19.39. The other estimates are pretty similar as well. They are not the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II Wald chisquare tests)

Response: fas
             Chisq Df Pr(&gt;Chisq)    
time       85.1243  1  &lt; 2.2e-16 ***
group       1.2932  1   0.255453    
time:group  6.7999  1   0.009116 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit3c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type II Wald chisquare tests)

Response: fas
             Chisq Df Pr(&gt;Chisq)    
time       84.9760  1    &lt; 2e-16 ***
group       0.7085  1    0.39994    
time:group  5.6695  1    0.01726 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value for both of the interaction terms are significant, thus the inference for the interaction term does not change.</p>
<p>The estimated variances of random effects for the intercept in the first model is 181.97, and 309.24, which are pretty different. For time, it is 6.475 and 6.487. The residual variance is nearly equal, at 27.638 and 27.622.</p>
<p>The main covariate effect of group varies more across individuals. This is because the variance is larger for group than it is for time</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>